config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'static#landing'
  match '/about', to: 'static#about', via: :get, as: 'about'
  match '/assessment-report', to: 'assessment_report#index', via: :get,
        as: 'assessment_report'
  match '/assessment-report/collections', to: 'assessment_report#collections_section',
        via: :get
  match '/assessment-report/preservation', to: 'assessment_report#preservation_section',
        via: :get
  match '/assessment-report/resources', to: 'assessment_report#resources_section',
        via: :get
  match '/assessment-report/storage', to: 'assessment_report#storage_section',
        via: :get
  match '/bibliography', to: 'static#bibliography', via: :get
  match '/dashboard', to: 'dashboard#index', via: :get
  match '/getting-started', to: 'static#getting_started', via: :get
  match '/glossary', to: 'static#glossary', via: :get

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :formats, only: [:index, :show] do
    # used for populating the new/edit resource form with assessment questions
    resources :assessment_questions, only: :index, path: 'assessment-questions'
  end
  # used for dependent select menus in forms
  resources :format_classes, only: [], path: 'format-classes' do
    resources :formats, only: :index, path: 'formats'
  end
  resources :institutions do
    match '/assess', to: 'institutions#assess', via: :get
    resources :repositories, except: :index
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    match '/export', to: 'institutions#export', via: :get
    # these are used for form autocompletion
    match '/resources/names', to: 'resources#names', via: :get
    match '/resources/subjects', to: 'resources#subjects', via: :get
  end
  match '/institutions/:id/report', to: 'institutions#report', via: :get,
        as: 'institution_report'

  resources :repositories, except: :index do
    resources :locations, except: :index
  end
  resources :locations, except: :index do
    match '/assess', to: 'locations#assess', via: :get
    match '/resources/import', to: 'resources#import', via: :post,
          as: 'resource_import_post'
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    resources :resources, except: :index
  end
  match '/resources/move', to: 'resources#move', via: :post,
        as: 'resource_move'
  match '/resources/search', to: 'resources#search', via: :get,
        as: 'resource_search'
  resources :resources, except: :index do
    match '/assess', to: 'resources#assess', via: :get
    match '/clone', to: 'resources#clone', via: :patch, as: 'resource_clone'
    match '/import', to: 'resources#import', via: :post, as: 'import_post'
    match '/move-tree', to: 'resources#move_tree', via: :get
    resources :resources, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, param: :username, path_names: { new: 'register' }
  match '/users/:username/confirm', to: 'users#confirm',
        via: :get, as: 'confirm_user'
  match '/users/:username/enable', to: 'users#enable',
        via: :patch, as: 'enable_user'
  match '/users/:username/disable', to: 'users#disable',
        via: :patch, as: 'disable_user'
  match '/users/:username/exists', to: 'users#exists',
        via: :get, as: 'user_exists'
  match '/users/:username/approve-institution', to: 'users#approve_institution',
        via: :patch, as: 'approve_user_institution'
  match '/users/:username/refuse-institution', to: 'users#refuse_institution',
        via: :patch, as: 'refuse_user_institution'
  match '/users/:username/send-confirmation-email',
        to: 'users#send_confirmation_email',
        via: :patch, as: 'send_confirmation_email'

  # Password routes
  # Step 1: "I forgot my password," click a button to POST to /forgot-password
  match '/forgot-password', to: 'password#forgot_password', via: :get
  match '/forgot-password', to: 'password#send_email', via: :post
  # Step 2: I click the link to /new-password in the email, then POST new
  # password to /new-password
  match '/new-password', to: 'password#new_password', via: :get
  match '/new-password', to: 'password#reset_password', via: :post

  # Collection ID Guide (formerly Format ID Guide) routes
  match '/collection-id-guide', to: 'collection_id_guide#index',
        via: :get, as: 'collection_id_guide'
  match '/collection-id-guide/search', to: 'collection_id_guide#search',
        via: :get, as: 'collection_id_guide_search'
  match '/collection-id-guide/:category', to: 'collection_id_guide#show',
        via: :get, as: 'collection_id_guide_category'

  # Redirect old Format ID Guide paths to Collection ID Guide paths
  get '/format-id-guide', to: redirect('/collection-id-guide')
  get '/format-id-guide/search', to: redirect('/collection-id-guide/search')
  get '/format-id-guide/:category', to: redirect('/collection-id-guide/%{category}')

  # Help routes
  match '/help', to: 'help#index', via: :get, as: 'help'
  match '/help/search', to: 'help#search', via: :get, as: 'help_search'
  match '/simple-help', to: 'help#simple_index', via: :get, as: 'simple_help'
  match '/advanced-help', to: 'help#advanced_index', via: :get,
        as: 'advanced_help'
  match '/advanced-help/:category', to: 'help#advanced_show', via: :get,
        as: 'advanced_help_category'
  match '/manual', to: 'help#manual', via: :get, as: 'user_manual'

end

app/controllers/help_controller.rb
class HelpController < ApplicationController

  ##
  # Responds to GET /advanced-help
  #
  def advanced_index
  end

  ##
  # Responds to GET /advanced-help/:category
  #
  def advanced_show
    @page = StaticPage.where(component: StaticPage::Component::HELP,
                             uri_fragment: params[:category]).first
    raise ActiveRecord::RecordNotFound unless @page
  end

  ##
  # Main help landing page. Responds to GET /help
  #
  def index
  end

  ##
  # Responds to GET /manual
  #
  def manual
    # there is only one user manual page
    @page = StaticPage.
        where(component: StaticPage::Component::USER_MANUAL).first
    raise ActiveRecord::RecordNotFound unless @page
  end

  ##
  # Responds to GET /search?q=...
  #
  def search
    @results = []
    if params[:q] and params[:q].length > 0
      @results = StaticPage.full_text_search(
          params[:q],
          [StaticPage::Component::HELP, StaticPage::Component::USER_MANUAL])
    end
    @query = params[:q].truncate(50)
    @results_summary = @query.length > 0 ?
        "Results for \"#{@query}\"" : "Help Search"
  end

  ##
  # Responds to GET /simple-help
  #
  def simple_index
  end

end

app/views/help/_results.html.erb
<% if @query.length > 0 %>
  <% if @results.any? %>
    <table class="table">
      <tbody>
        <% @results.each_with_index do |result, index| %>
          <% page = StaticPage.find(result['id']) %>
          <tr>
            <td class="psap-index"><%= index + 1 %></td>
            <td>
              <% dest = nil %>
              <% case page.component %>
                <% when StaticPage::Component::HELP %>
                  <% dest = advanced_help_category_path(page) %>
                <% when StaticPage::Component::USER_MANUAL %>
                  <% dest = user_manual_path %>
              <% end %>
              <%= link_to page.name, dest %>
            </td>
            <td><%= raw(result['highlight']) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No results.</p>
  <% end %>
<% else %>
  <p>Enter a query in the text field above.</p>
<% end %>

app/views/help/_search_field.html.erb
<form method="get" action="<%= help_search_path %>"
      class="form-inline pull-right">
  <div class="input-group">
    <span class="input-group-addon"><i class="fa fa-search"></i></span>
    <%= search_field_tag :q, params[:q], class: 'form-control' %>
    <span class="input-group-btn">
      <input type="submit" value="Search Help" class="btn btn-default">
    </span>
  </div>
</form>

app/views/help/advanced_index.html.erb
<% provide(:title, 'Advanced Help') %>

<ol class="breadcrumb">
  <li>
    <%= link_to 'Help', help_path %>
  </li>
  <li class="active">Advanced Help</li>
</ol>

<div class="pull-right">
  <%= render partial: 'search_field' %>
</div>

<div class="psap-page-title">
  <h1>Advanced Help</h1>
</div>

<ul>
  <li>Audiovisual Formats
    <ul>
      <li><%= link_to 'Audiocassettes', advanced_help_category_path('av-audiocassette') %></li>
      <li><%= link_to 'Cylinders', advanced_help_category_path('av-cylinder') %></li>
      <li><%= link_to 'Film', advanced_help_category_path('av-film') %></li>
      <li><%= link_to 'Open Reel Audio', advanced_help_category_path('av-audioopenreel') %></li>
      <li><%= link_to 'Open Reel Video', advanced_help_category_path('av-videoopenreel') %></li>
      <li><%= link_to 'Optical Media', advanced_help_category_path('av-opticalmedia') %></li>
      <li><%= link_to 'Phonographic Discs', advanced_help_category_path('av-phonodisc') %></li>
      <li><%= link_to 'Wire Recordings', advanced_help_category_path('av-wire') %></li>
    </ul>
  </li>
  <li>Digital Prints
    <ul>
      <li><%= link_to 'Inkjet', advanced_help_category_path('digital-inkjet') %></li>
    </ul>
  </li>
  <li><%= link_to 'Paper (Bound)', advanced_help_category_path('paper-bound-book') %></li>
  <li>Paper (Unbound)
    <ul>
      <li>Architectural Reproductions
        <ul>
          <li><%= link_to 'Aniline Prints', advanced_help_category_path('paper-unbound-architectural-aniline') %></li>
          <li><%= link_to 'Blueprints', advanced_help_category_path('paper-unbound-architectural-blueprint') %></li>
          <li><%= link_to 'Diazo', advanced_help_category_path('paper-unbound-architectural-diazo') %></li>
          <li><%= link_to 'Ferrogallic', advanced_help_category_path('paper-unbound-architectural-ferrogallic') %></li>
          <li><%= link_to 'Hectograph', advanced_help_category_path('paper-unbound-architectural-hectograph') %></li>
          <li><%= link_to 'Photostatic', advanced_help_category_path('paper-unbound-architectural-photostat') %></li>
          <li><%= link_to 'Unidentified Formats', advanced_help_category_path('paper-unbound-architectural-unidentified') %></li>
          <li><%= link_to 'Van Dyke', advanced_help_category_path('paper-unbound-architectural-vandyke') %></li>
          <li><%= link_to 'Wash-off', advanced_help_category_path('paper-unbound-architectural-washoff') %></li>
        </ul>
      <li>Office Copies
        <ul>
          <li><%= link_to 'Carbonless Paper', advanced_help_category_path('paper-unbound-officecopy-carbonless') %></li>
          <li><%= link_to 'Copybooks', advanced_help_category_path('paper-unbound-officecopy-copybook') %></li>
          <li><%= link_to 'Diazo Prints', advanced_help_category_path('paper-unbound-officecopy-diazo') %></li>
          <li><%= link_to 'Dye Ink Transfer', advanced_help_category_path('paper-unbound-officecopy-dyeinktransfer') %></li>
          <li><%= link_to 'Electrofax', advanced_help_category_path('paper-unbound-officecopy-electrofax') %></li>
          <li><%= link_to 'Electrostatic/Photocopy (Black)', advanced_help_category_path('paper-unbound-officecopy-electrostatic') %></li>
          <li><%= link_to 'Electrostatic/Photocopy (Color)', advanced_help_category_path('paper-unbound-officecopy-electrostatic-colorphotocopy') %></li>
          <li><%= link_to 'Inkjet', advanced_help_category_path('paper-unbound-officecopy-inkjet') %></li>
          <li><%= link_to 'Ink on Paper', advanced_help_category_path('paper-unbound-officecopy-inkonpaper') %></li>
          <li>Photographic
            <ul>
              <li><%= link_to 'Diffusion Transfer', advanced_help_category_path('paper-unbound-officecopy-photographic-diffusiontransfer') %>
              <li><%= link_to 'Photostatic', advanced_help_category_path('paper-unbound-officecopy-photographic-photostat') %>
            </ul>
          <li><%= link_to 'Thermal', advanced_help_category_path('paper-unbound-officecopy-thermal') %></li>
          <li><%= link_to 'Unidentified Formats' , advanced_help_category_path('paper-unbound-officecopy-unidentified') %></li>
        </ul>
      <li><%= link_to 'Original Documents', advanced_help_category_path('paper-unbound-originaldoc')%></li>
    </ul>
  </li>
  <li>Photographic Images
    <ul>
      <li>Color
        <ul>
          <li><%= link_to 'Chromogenic', advanced_help_category_path('photo-color-chromogenic') %></li>
          <li><%= link_to 'Color Carbro', advanced_help_category_path('photo-color-colorcarbro') %></li>
          <li><%= link_to 'Dye Transfer', advanced_help_category_path('photo-color-dyetransfer') %></li>
          <li><%= link_to 'Silver Dye Bleach', advanced_help_category_path('photo-color-silverdyebleach') %></li>
        </ul>
      <li>Direct Photographic Prints
        <ul>
          <li><%= link_to 'Ambrotypes', advanced_help_category_path('direct-ambrotype') %></li>
          <li><%= link_to 'Daguerreotypes', advanced_help_category_path('direct-daguerreotype') %></li>
          <li><%= link_to 'Tintypes', advanced_help_category_path('direct-tintype') %></li>
        </ul>
      <li>Instant Photographs
        <ul>
          <li><%= link_to 'Black and White', advanced_help_category_path('photo-instant-bw') %></li>
          <li><%= link_to 'Color', advanced_help_category_path('photo-instant-color') %></li>
        </ul>
      <li>Monochromatic
        <ul>
          <li><%= link_to 'Carbon/Woodburytype', advanced_help_category_path('photo-monochrome-carbon-woodburytype') %></li>
          <li><%= link_to 'Cyanotype', advanced_help_category_path('photo-monochrome-cyanotype') %></li>
          <li><%= link_to 'Glossy Collodion', advanced_help_category_path('photo-monochrome-glossycollodion') %></li>
          <li><%= link_to 'Matte Collodion', advanced_help_category_path('photo-monochrome-mattecollodion') %></li>
          <li><%= link_to 'Platinum/Palladium', advanced_help_category_path('photo-monochrome-platinum-palladium') %></li>
          <li><%= link_to 'Salt', advanced_help_category_path('photo-monochrome-salt') %></li>
          <li><%= link_to 'Silver Gelatin Printing Out Process (POP)', advanced_help_category_path('photo-monochrome-gelatinpop') %></li>
          <li><%= link_to 'Silver Gelatin Developing Out Process (DOP)', advanced_help_category_path('photo-monochrome-silvergelatin') %></li>
        </ul>
      <li><%= link_to 'Microforms', advanced_help_category_path('microform') %></li>
      <li>Negatives
        <ul>
          <li><%= link_to 'Chromogenic', advanced_help_category_path('negative-chromogenic') %></li>
          <li><%= link_to 'Glass', advanced_help_category_path('negative-glass') %></li>
          <li><%= link_to 'Silver Gelatin', advanced_help_category_path('negative-silvergelatin') %></li>
        </ul>
      </li>
      <li>Transparencies/Slides
        <ul>
          <li>Film
            <ul>
              <li><%= link_to 'Black and White', advanced_help_category_path('slide-film-bw') %></li>
              <li><%= link_to 'Color', advanced_help_category_path('slide-film-color') %></li>
            </ul>
          <li>Glass
            <ul>
              <li><%= link_to 'Autochrome', advanced_help_category_path('slide-glass-autochrome') %></li>
              <li><%= link_to 'Black and White', advanced_help_category_path('slide-glass-bw') %></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </li>
  <li><%= link_to 'Photomechanical Prints', advanced_help_category_path('photomechanical') %></li>
  <li>Objects
    <ul>
      <li><%= link_to 'Ceramic', advanced_help_category_path('advhelp-ceramics') %></li>
      <li><%= link_to 'Glass', advanced_help_category_path('advhelp-glass') %></li>
      <li><%= link_to 'Stone', advanced_help_category_path('advhelp-stone') %></li>
      <li><%= link_to 'Metal', advanced_help_category_path('advhelp-metal') %></li>
    </ul>
  </li>
  <li>Supplementary Documentation
    <ul>
      <li><%= link_to 'Institution', advanced_help_category_path('institution') %></li>
      <li><%= link_to 'Location', advanced_help_category_path('location') %></li>
      <li><%= link_to 'Significance', advanced_help_category_path('supplementary-significance') %></li>
    </ul>
  </li>
</ul>

app/views/help/advanced_show.html.erb
<% provide(:body_id, 'help_page') %>
<% provide(:title, @page.name) %>

<ol class="breadcrumb">
  <li>
    <%= link_to 'Help', help_path %>
  </li>
  <li>
    <%= link_to 'Advanced Help', advanced_help_path %>
  </li>
  <li class="active"><%= @page.name %></li>
</ol>

<div class="pull-right">
  <%= render partial: 'search_field' %>
</div>

<div class="psap-page-title"></div>

<%= static_page_html(@page.html) %>

app/views/help/index.html.erb
<% provide :title, 'Help' %>
<% provide :body_id, 'help' %>

<div class="pull-right">
  <%= render partial: 'search_field' %>
</div>

<div class="psap-page-title">
  <h1>Help</h1>
</div>

<p>You have arrived at the hub for PSAP help. Depending on your needs, the PSAP offers several levels of help. See the sections below to determine which feature is best suited to your circumstance.</p>

<ul>
  <li><%= link_to 'Getting Started', getting_started_path %> is a graphic guide for new users navigating the application for the first time.</li>
  <li><%= link_to 'Simple Help', simple_help_path %> is designed to provide basic assistance in understanding how to answer assessment questions.</li>
  <li><%= link_to 'Advanced Help', advanced_help_path %> is designed to provide in-depth guidance and context for each question asked during assessment.</li>
  <li>The <%= link_to 'Collection ID Guide', collection_id_guide_path %> is designed to assist with identifying the format and base materials of your resources.  It also provides a number of reference and supplementary guides to help establish institutional policies and to support continuing education of staff and volunteers.</li>
  <li>The <%= link_to 'User Manual', user_manual_path %> is designed to assist with understanding and using the application.</li>
</ul>

<h2>Tutorial Videos</h2>
<p>Take a look at our short instructional videos to orient yourself if you are new to the application.</p>
<iframe width="560" height="315"
        src="https://www.youtube.com/embed/videoseries?list=PL2KBG6GWVkS-kCHb5iljwIZALS4Hxzkum"
        frameborder="0" allowfullscreen></iframe>

<h2>Which help feature is right for me?</h2>

<h3>Do you need a quick, graphic guide to get you started with the tool?</h3>
<p><%= link_to 'Click through to Getting Started.', getting_started_path %></p>

<h3>Do you need help using the PSAP tool, understanding how to enter your resources, generating reports, or navigating the application?</h3>
<p><%= link_to 'Click through to the User Manual.', user_manual_path %></p>

<h3>Do you need help understanding how to answer the assessment questions you are being asked, or do you need to know more about why we are asking particular questions?</h3>
<p><%= link_to 'Click through to Simple Help.', simple_help_path %></p>
<p><%= link_to 'Click through to Advanced Help.', advanced_help_path %></p>

<h3>Do you need help identifying the format of your resource, or do you need to learn more about the history and best practices associated with a format?</h3>
<p><%= link_to 'Click through to the Collection ID Guide.', collection_id_guide_path %></p>
<p><%= link_to 'Click through to Advanced Help.', advanced_help_path %></p>

<h2>Other Resources</h2>
<ul>
  <li>The PSAP <%= link_to 'Glossary', glossary_path %> provides definitions of terms that are commonly used in the application.</li>
  <li>The PSAP <%= link_to 'Bibliography', bibliography_path %> contains all of the reference material used in the development of preservation recommendations.</li>
  <li>The PSAP project <a href="http://www.library.illinois.edu/prescons/projects_grants/grants/PSAP/">website</a> on the University of Illinois' library page provides information about support, partners, and project development.</li>
  <li>The PSAP <a href="https://github.com/PresConsUIUC/PSAP/">GitHub</a> contains the openly available code for the application.</li>
  <li>The contact email for the project is <a href="mailto:psap@library.illinois.edu?Subject=Assistance%20requested">psap@library.illinois.edu</a> - please contact us if you have a question that cannot be resolved with our help features. Comments and bug reports are also gratefully accepted.</li>
</ul>

app/views/help/manual.html.erb
<% provide(:title, 'User Manual') %>
<% provide(:body_id, 'user_manual_page') %>

<ol class="breadcrumb">
  <li>
    <%= link_to 'Help', help_path %>
  </li>
  <li class="active">User Manual</li>
</ol>

<div class="pull-right">
  <%= render partial: 'search_field' %>
</div>

<div class="psap-page-title">
  <h1>User Manual</h1>
</div>

<%= static_page_html(@page.html) %>

app/views/help/search.html.erb
<% provide(:body_id, 'help_results') %>
<% provide(:title, 'Help') %>

<ol class="breadcrumb">
  <li>
    <%= link_to 'Help', help_path %>
  </li>
  <li class="active">Search</li>
</ol>

<div class="pull-right">
  <form method="get" action="" class="form-inline psap-live-search"
        style="float:right; max-width:100%">
    <div class="input-group">
      <span class="input-group-addon"><i class="fa fa-search"></i></span>
      <%= search_field_tag :q, params[:q], placeholder: 'Search', class: 'form-control' %>
    </div>
  </form>
</div>

<div class="psap-page-title">
  <h1 class="results-summary"><%= @results_summary %></h1>
</div>

<div id="results">
  <%= render 'results' %>
</div>