config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'static#landing'
  match '/about', to: 'static#about', via: :get, as: 'about'
  match '/assessment-report', to: 'assessment_report#index', via: :get,
        as: 'assessment_report'
  match '/assessment-report/collections', to: 'assessment_report#collections_section',
        via: :get
  match '/assessment-report/preservation', to: 'assessment_report#preservation_section',
        via: :get
  match '/assessment-report/resources', to: 'assessment_report#resources_section',
        via: :get
  match '/assessment-report/storage', to: 'assessment_report#storage_section',
        via: :get
  match '/bibliography', to: 'static#bibliography', via: :get
  match '/dashboard', to: 'dashboard#index', via: :get
  match '/getting-started', to: 'static#getting_started', via: :get
  match '/glossary', to: 'static#glossary', via: :get

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :formats, only: [:index, :show] do
    # used for populating the new/edit resource form with assessment questions
    resources :assessment_questions, only: :index, path: 'assessment-questions'
  end
  # used for dependent select menus in forms
  resources :format_classes, only: [], path: 'format-classes' do
    resources :formats, only: :index, path: 'formats'
  end
  resources :institutions do
    match '/assess', to: 'institutions#assess', via: :get
    resources :repositories, except: :index
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    match '/export', to: 'institutions#export', via: :get
    # these are used for form autocompletion
    match '/resources/names', to: 'resources#names', via: :get
    match '/resources/subjects', to: 'resources#subjects', via: :get
  end
  match '/institutions/:id/report', to: 'institutions#report', via: :get,
        as: 'institution_report'

  resources :repositories, except: :index do
    resources :locations, except: :index
  end
  resources :locations, except: :index do
    match '/assess', to: 'locations#assess', via: :get
    match '/resources/import', to: 'resources#import', via: :post,
          as: 'resource_import_post'
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    resources :resources, except: :index
  end
  match '/resources/move', to: 'resources#move', via: :post,
        as: 'resource_move'
  match '/resources/search', to: 'resources#search', via: :get,
        as: 'resource_search'
  resources :resources, except: :index do
    match '/assess', to: 'resources#assess', via: :get
    match '/clone', to: 'resources#clone', via: :patch, as: 'resource_clone'
    match '/import', to: 'resources#import', via: :post, as: 'import_post'
    match '/move-tree', to: 'resources#move_tree', via: :get
    resources :resources, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, param: :username, path_names: { new: 'register' }
  match '/users/:username/confirm', to: 'users#confirm',
        via: :get, as: 'confirm_user'
  match '/users/:username/enable', to: 'users#enable',
        via: :patch, as: 'enable_user'
  match '/users/:username/disable', to: 'users#disable',
        via: :patch, as: 'disable_user'
  match '/users/:username/exists', to: 'users#exists',
        via: :get, as: 'user_exists'
  match '/users/:username/approve-institution', to: 'users#approve_institution',
        via: :patch, as: 'approve_user_institution'
  match '/users/:username/refuse-institution', to: 'users#refuse_institution',
        via: :patch, as: 'refuse_user_institution'
  match '/users/:username/send-confirmation-email',
        to: 'users#send_confirmation_email',
        via: :patch, as: 'send_confirmation_email'

  # Password routes
  # Step 1: "I forgot my password," click a button to POST to /forgot-password
  match '/forgot-password', to: 'password#forgot_password', via: :get
  match '/forgot-password', to: 'password#send_email', via: :post
  # Step 2: I click the link to /new-password in the email, then POST new
  # password to /new-password
  match '/new-password', to: 'password#new_password', via: :get
  match '/new-password', to: 'password#reset_password', via: :post

  # Collection ID Guide (formerly Format ID Guide) routes
  match '/collection-id-guide', to: 'collection_id_guide#index',
        via: :get, as: 'collection_id_guide'
  match '/collection-id-guide/search', to: 'collection_id_guide#search',
        via: :get, as: 'collection_id_guide_search'
  match '/collection-id-guide/:category', to: 'collection_id_guide#show',
        via: :get, as: 'collection_id_guide_category'

  # Redirect old Format ID Guide paths to Collection ID Guide paths
  get '/format-id-guide', to: redirect('/collection-id-guide')
  get '/format-id-guide/search', to: redirect('/collection-id-guide/search')
  get '/format-id-guide/:category', to: redirect('/collection-id-guide/%{category}')

  # Help routes
  match '/help', to: 'help#index', via: :get, as: 'help'
  match '/help/search', to: 'help#search', via: :get, as: 'help_search'
  match '/simple-help', to: 'help#simple_index', via: :get, as: 'simple_help'
  match '/advanced-help', to: 'help#advanced_index', via: :get,
        as: 'advanced_help'
  match '/advanced-help/:category', to: 'help#advanced_show', via: :get,
        as: 'advanced_help_category'
  match '/manual', to: 'help#manual', via: :get, as: 'user_manual'

end

app/models/institution.rb
##
# An institution is a top-level entity containing zero or more Repositories.
# Once assigned to an institution, users (except administrators) are restricted
# to accessing entities related to that institution.
#
# Institutions are assessable.
#
class Institution < ApplicationRecord

  include Assessable

  has_and_belongs_to_many :assessment_questions
  has_many :assessment_question_responses, inverse_of: :institution,
           dependent: :destroy
  has_many :desiring_users, class_name: 'User', inverse_of: :desired_institution,
           dependent: :restrict_with_exception
  has_many :users, -> { order(:last_name) }, inverse_of: :institution,
           dependent: :restrict_with_exception
  has_many :repositories, -> { order(:name) }, inverse_of: :institution,
           dependent: :destroy
  belongs_to :language, inverse_of: :institutions, optional: true
  has_many :locations, -> { order(:name) }, through: :repositories
  has_many :resources, -> { order(:name) }, through: :locations

  accepts_nested_attributes_for :assessment_question_responses

  validates :address1, presence: true, length: { maximum: 255 }
  validates :address2, length: { maximum: 255 }
  validates :city, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { minimum: 4, maximum: 255 },
            uniqueness: { case_sensitive: false }
  validates :state, length: { maximum: 30 }
  validates :postal_code, length: { maximum: 30 }
  validates :country, presence: true, length: { maximum: 255 }
  validates :url, allow_blank: true, format: URI::regexp(%w(http https))

  ##
  # Imports data exported from `full_export_as_json()`. All existing associated
  # data (except users) is deleted first.
  #
  # @param struct [Hash]
  # @return [void]
  #
  def self.import(struct)
    ActiveRecord::Base.transaction do
      # Destroy most of the institution's content (except users) in
      # order to make way for the imported content.
      inst = Institution.find(struct['id'].to_i)
      inst.assessment_question_responses.destroy_all
      inst.repositories.destroy_all

      struct['assessment_question_responses'].each do |response|
        inst.assessment_question_responses.build(
            assessment_question_option_id: response['assessment_question_option_id'],
            assessment_question_id: response['assessment_question_id'],
            created_at: response['created_at'],
            updated_at: response['updated_at'])
      end
      struct['repositories'].each do |repo|
        Repository.import(repo, inst.id)
      end
      inst.save!
      inst
    end
  end

  ##
  # @return Array of all assessed items in an institution, regardless of depth
  # in the hierarchy.
  #
  def all_assessed_items
    self.resources.where(assessment_complete: true)
  end

  ##
  # Returns a hash containing statistics of all assessed items in the
  # institution.
  #
  # @return [Hash] Hash with mean, median, low, and high keys
  #
  def assessed_item_statistics
    stats = { mean: 0, median: 0, low: 0, high: 0 }
    all_items = all_assessed_items
    all_items_count = all_items.count
    if all_items_count < 1
      return stats
    end

    all_items.each do |item|
      stats[:high] = item.assessment_score if item.assessment_score > stats[:high]
      stats[:low]  = item.assessment_score if
          stats[:low].nil? or item.assessment_score < stats[:low]
    end
    all_scores     = all_items.pluck(:assessment_score)
    stats[:mean]   = all_scores.sum.to_f / all_items_count.to_f
    sorted         = all_scores.sort
    len            = sorted.length
    stats[:median] = (sorted[(len - 1) / 2] + sorted[len / 2]) / 2.0
    stats
  end

  ##
  # @return Array of all assessed locations in an institution.
  #
  def assessed_locations
    self.locations.where(assessment_complete: true)
  end

  ##
  # Exports all of an instance's associated content, except users, to enable
  # recovery of user-deleted data. To do this:
  #
  # 1. Stand up a second instance of the application
  # 2. Load its database with backup data
  # 3. Invoke this method and capture the return value (typically via a rake
  #    task)
  # 4. Pass the returned JSON to `import()` (typically via a rake task) on the
  #    production application instance
  #
  # @return [Hash] Hash that can be passed to JSON.generate()
  #
  def full_export_as_json
    struct = self.as_json
    struct[:assessment_question_responses] =
        self.assessment_question_responses.map(&:as_json)
    struct[:repositories] = self.repositories.map(&:full_export_as_json)
    struct
  end

  ##
  # @param section AssessmentSection
  # @return float
  #
  def mean_assessed_item_score_in_section(section)
    score = 0.0
    assessed_items = all_assessed_items
    return score if assessed_items.length < 1

    assessed_items.each do |item|
      score += item.assessment_score_in_section(section)
    end
    score.to_f / assessed_items.length.to_f
  end

  ##
  # @param section AssessmentSection
  # @return float
  #
  def mean_assessed_location_score_in_section(section)
    score = 0.0
    assessed_locations = self.assessed_locations
    return score if assessed_locations.length < 1

    assessed_locations.each do |location|
      score += location.assessment_score_in_section(section)
    end
    score / assessed_locations.length.to_f
  end

  def mean_location_score
    locations_ = locations.where(assessment_complete: true)
    count = locations_.count
    count > 0 ? locations_.pluck(:assessment_score).sum.to_f / count.to_f : 0.0
  end

  def mean_resource_score
    items = resources.where(resource_type: Resource::Type::ITEM,
                            assessment_complete: true)
    count = items.count
    count > 0 ? items.pluck(:assessment_score).sum.to_f / count.to_f : 0.0
  end

  def to_s
    "#{self.name}"
  end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController

  before_action :signed_in_user
  before_action :admin_user, only: [:index, :destroy]
  before_action :same_institution_user, except: [:create, :destroy, :index,
                                                 :new]

  def assess
    if request.xhr?
      @institution = Institution.find(params[:institution_id])
      @assessment_sections = Assessment.find_by_key('institution').
          assessment_sections.order(:index)
      render partial: 'assess_form', locals: { action: :assess }
    else
      render status: 406, plain: 'Not Acceptable'
    end
  end

  def create
    create_command = CreateInstitutionCommand.new(
        institution_params, current_user, request.remote_ip)
    @institution = create_command.object
    begin
      ActiveRecord::Base.transaction do
        create_command.execute
        unless current_user.is_admin?
          join_command = JoinInstitutionCommand.new(current_user,
                                                    @institution, current_user,
                                                    request.remote_ip)
          join_command.execute
        end
      end
    rescue ValidationError
      response.headers['X-Psap-Result'] = 'error'
      render partial: 'shared/validation_messages',
             locals: { entity: @institution }
    rescue => e
      response.headers['X-Psap-Result'] = 'error'
      flash['error'] = "#{e}"
      render 'create'
    else
      response.headers['X-Psap-Result'] = 'success'
      if current_user.is_admin?
        flash['success'] = "The institution \"#{@institution.name}\" has been "\
        "created."
        prepare_index_view
        render 'create'
      else
        flash['success'] = "The institution \"#{@institution.name}\" has been "\
          "created. An administrator has been notified and will review your "\
          "request to join it soon."
      end
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    command = DeleteInstitutionCommand.new(@institution, current_user,
                                           request.remote_ip)
    begin
      command.execute
    rescue => e
      flash['error'] = "#{e}"
      redirect_to institution_url(@institution)
    else
      flash['success'] = "Institution \"#{@institution.name}\" deleted."
      redirect_to institutions_url
    end
  end

  def edit
    if request.xhr?
      @institution = Institution.find(params[:id])
      render partial: 'edit_form', locals: { action: :edit }
    else
      render status: 406, plain: 'Not Acceptable'
    end
  end

  def export
    institution = Institution.find(params[:institution_id])
    send_data JSON.pretty_generate(institution.full_export_as_json),
              type:        'application/json',
              filename:    'full_export.json',
              disposition: 'attachment'
  end

  def index
    prepare_index_view
  end

  def new
    if request.xhr?
      @institution = Institution.new
      render partial: 'edit_form', locals: { action: :create }
    else
      render status: 406, plain: 'Not Acceptable'
    end
  end

  def show
    prepare_show_view
  end

  def update
    @institution = Institution.find(params[:id])
    command = UpdateInstitutionCommand.new(@institution, institution_params,
                                           current_user, request.remote_ip)
    begin
      command.execute
    rescue ValidationError
      response.headers['X-Psap-Result'] = 'error'
      render partial: 'shared/validation_messages',
             locals: { entity: @institution }
    rescue => e
      response.headers['X-Psap-Result'] = 'error'
      flash['error'] = "#{e}"
      render 'info'
    else
      prepare_show_view
      response.headers['X-Psap-Result'] = 'success'
      flash['success'] = "Institution \"#{@institution.name}\" updated."
      render 'info'
    end
  end

  private

  def prepare_index_view
    @institutions = Institution.order(:name).paginate(
        page: params[:page],
        per_page: ::Configuration.instance.results_per_page)
  end

  def prepare_show_view
    @institution = Institution.find(params[:id])

    # data for repositories tab
    @repositories = @institution.repositories.order(:name).
        paginate(page: params[:page],
                 per_page: ::Configuration.instance.results_per_page)

    # data for users tab
    @institution_users = @institution.users.where(confirmed: true).order(:last_name)
  end

  def same_institution_user
    # Normal users can only edit their own institution. Administrators can edit
    # any institution.
    institution = Institution.find(params[:id] || params[:institution_id])
    redirect_to(root_url) unless
        institution.users.include?(current_user) or current_user.is_admin?
  end

  def institution_params
    params.require(:institution).permit(:address1, :address2, :city, :country,
                                        :description, :email, :language_id,
                                        :name, :postal_code, :state, :url).tap do |whitelisted|
      # AQRs don't use Rails' nested params format, and will require additional
      # processing
      whitelisted[:assessment_question_responses] =
          params[:institution][:assessment_question_responses] if
          params[:institution][:assessment_question_responses]
    end
  end

end

app/views/institutions/_assess_form.html.erb
<%= form_for(@institution, remote: true) do |f| %>
  <% @institution.assessment_question_responses.each do |response| %>
    <input type="hidden" name="selected_option_ids"
           value="<%= response.assessment_question_option.id %>">
  <% end %>

  <% @assessment_sections.each_with_index do |section, index| %>
    <%= render partial: 'shared/section_form',
               locals: { section: section,
                         draw_bottom_rule: index < @assessment_sections.length - 1 } %>
  <% end %>

  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
  <%= f.submit 'Assess Institution', class: 'btn btn-primary' %>

<% end %>

app/views/institutions/_edit_form.html.erb
<%= form_for(@institution, remote: true) do |f| %>

  <div class="psap-error-messages">
    <% # populated via ajax by _show_error.js.erb
    %>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :name, class: 'required' %>
    <%= f.text_field :name, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :url, 'URL' %>
    <%= f.url_field :url, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :address1, 'Address 1', class: 'required' %>
    <%= f.text_field :address1, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :address2, 'Address 2' %>
    <%= f.text_field :address2, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :city, class: 'required' %>
    <%= f.text_field :city, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group has-feedback">
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code, class: 'form-control' %>
    <span class="glyphicon form-control-feedback"></span>
  </div>

  <div class="form-group">
    <%= f.label :country, class: 'required' %>
    <%= select('institution', 'country', countries_for_select,
               { include_blank: false },
               { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label :language %>
    <%= f.collection_select :language_id, Language.all, :id, :english_name,
                            { include_blank: true },
                            { class: 'form-control input-md' } %>
  </div>

  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
  <%= f.submit(action == :create ? 'Create Institution' : 'Save Changes',
               class: 'btn btn-primary') %>

<% end %>

app/views/institutions/_export_assessment_report_pdf.html.erb
<div class="dropdown pull-right">
  <button class="btn btn-default dropdown-toggle" type="button"
          id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
    <i class="fa fa-file-pdf-o"></i> Export PDF
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
    <% if section %>
      <li role="presentation">
        <a role="menuitem" tabindex="-1"
           href="<%= "#{institution_assessment_report_path(@institution)}.pdf?section=#{section}" %>">This Section</a>
      </li>
    <% end %>
    <li role="presentation">
      <a role="menuitem" tabindex="-1"
         href="<%= institution_assessment_report_path(@institution) + '.pdf' %>">Entire Report</a>
    </li>
  </ul>
</div>

app/views/institutions/_institutions.html.erb
<% # Will be read by PSAP.updateResultsCount() in JS %>
<input type="hidden" name="results_count" value="<%= @institutions.total_entries %>">

<ul class="institutions psap-entity-list">
  <% @institutions.each do |institution| %>
      <li>
        <span class="title"><%= link_to institution.name, institution %></span>
        <small>
          <%= entity_icon(Repository, pluralize(institution.repositories.count, 'repository')) %>
          <%= institution.repositories.count %>
          <%= entity_icon(Resource, pluralize(institution.resources.count, 'resource')) %>
          <%= institution.resources.count %>
          <%= entity_icon(User, pluralize(institution.users.count, 'user')) %>
          <%= institution.users.count %>
        </small>
        <br>
        <span class="description"><%= institution.description %></span>
      </li>
  <% end %>
</ul>

<div class="text-center">
  <%= will_paginate @institutions, renderer: BootstrapPagination::Rails %>
</div>

app/views/institutions/_show.html.erb
<div class="btn-group pull-right">
  <!-- Edit -->
  <button type="button" class="btn btn-default" data-toggle="modal"
          data-target="#psap-edit-panel">
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  </button>
  <!-- Assess -->
  <button type="button"
          class="btn btn-default <%= @institution.assessment_complete ? '' : 'btn-success' %>"
          data-toggle="modal"
          data-target="#psap-assess-panel">
    <span class="glyphicon glyphicon-stats"></span>
    Assess Institution
  </button>
  <!-- Delete -->
  <% if current_user.is_admin? %>
      <%= link_to institution_path(@institution), method: 'delete',
                  class: 'btn btn-danger',
                  disabled: @institution.users.any?,
                  data: { confirm: 'Deleting this institution will '\
                'delete ALL of its repositories, locations, and '\
                'resources along with it. Are you sure you want '\
                'to do this?' } do %>
          <%= content_tag(:span, '', class: 'glyphicon glyphicon-trash') %>
          Delete
      <% end %>
  <% end %>
</div>

<div class="psap-page-title">
  <h1><span id="institution_name"><%= @institution.name %></span>
    <small class="text-nowrap">
      <%= entity_icon(@institution) %>Institution
    </small>
  </h1>
  <% if @institution.description %>
      <p><%= @institution.description %></p>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-4 psap-entity-nav-menu">
    <%= render partial: 'shared/entity_hierarchy',
               locals: { selected_entity: @institution } %>
  </div>
  <div class="col-sm-8">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active">
        <a href="#repositories_tab" data-toggle="tab">Repositories</a>
      </li>
      <li role="presentation">
        <a href="#info_tab" data-toggle="tab">Info</a>
      </li>
      <li role="presentation">
        <a href="#score_summary_tab" data-toggle="tab">Score Summary
          <span class="badge"><%= number_to_human(@institution.assessment_score * 100) %></span>
        </a>
      </li>
      <li role="presentation">
        <a href="#users_tab" data-toggle="tab">Users</a>
      </li>
      <li role="presentation">
        <a href="#tools_tab" data-toggle="tab">Tools</a>
      </li>
    </ul>

    <div class="tab-content">

      <div class="tab-pane active" id="repositories_tab">
        <%= hidden_field_tag(:new_repository_url, new_institution_repository_url(@institution)) %>

        <!-- Add Repository button -->
        <div style="text-align:right">
          <%= entity_button(Repository, 'Add Repository',
                            { class: 'btn-success',
                              'data-toggle' => 'modal',
                              'data-target' => '#psap-create-panel' }) %>
        </div>

        <% if @repositories.any? %>
            <div id="repositories">
              <ul class="psap-entity-list">
                <% @repositories.each do |repository| %>
                    <li>
                    <span class="title">
                      <%= entity_icon(repository) %>
                      <%= link_to repository.name, repository %>
                    </span>
                      <small>
                        <%= entity_icon(Location, pluralize(repository.locations.count, 'location')) %>
                        <%= repository.locations.count %>

                        <%= entity_icon(Resource, pluralize(repository.resources.count, 'resource')) %>
                        <%= repository.resources.count %>
                      </small>
                    </li>
                <% end %>
              </ul>
              <div class="text-center">
                <%= will_paginate @repositories, renderer: BootstrapPagination::Rails %>
              </div>
            </div>
        <% else %>
            <p>This institution has no repositories.</p>
        <% end %>
      </div>

      <div class="tab-pane" id="info_tab">
        <dl>
          <dt>URL</dt>
          <dd><%= link_to @institution.url, @institution.url %></dd>
          <dt>Email</dt>
          <dd><a href="mailto:<%= @institution.email %>"><%= @institution.email %></a></dd>
          <dt>Address</dt>
          <dd>
            <%= @institution.address1 %>
            <% if @institution.address2 and !@institution.address2.empty? %>
                <br><%= @institution.address2 %>
            <% end %>
            <br><%= @institution.city %>, <%= @institution.state %> <%= @institution.postal_code %>
            <br><%= @institution.country %>
          </dd>
          <% if @institution.language %>
              <dt>Language</dt>
              <dd><%= @institution.language.english_name %></dd>
          <% end %>
          <dt>Created</dt>
          <dd><%= local_time_ago(@institution.created_at) %></dd>
          <dt>Last Updated</dt>
          <dd><%= local_time_ago(@institution.updated_at) %></dd>
        </dl>
      </div>

      <div class="tab-pane" id="score_summary_tab">
        <%= render partial: 'shared/assessable_report',
                   locals: { assessable: @institution } %>
      </div>

      <div class="tab-pane" id="users_tab">
        <% if @institution.users.any? %>
            <ul class="psap-user-list">
              <% @institution_users.each do |user| %>
                  <li>
                    <%= link_to user do %>
                        <%= gravatar_for user, size: 52 %>
                    <% end %>
                    <%= link_to user.full_name, user %>
                    <small><%= user.username %></small>
                  </li>
              <% end %>
            </ul>
        <% else %>
            <p>There are no users affiliated with this institution.</p>
        <% end %>
      </div>

      <div class="tab-pane" id="tools_tab">
        <div class="text-center">
          <%= link_to institution_export_path(@institution),
                      class: 'btn btn-primary btn-lg' do %>
            <%= content_tag(:span, '', class: 'glyphicon glyphicon-export') %>
            Full Export
          <% end %>
          <p class="help-block">A full export includes all information associated
            with this institution, except users, in JSON format.</p>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/institutions/create.js.erb
// Rendered by InstitutionsController upon a successful create by an
// administrator
<% if (@institution.id and current_user.institution == @institution) or
       current_user.is_admin? %>
  //window.location.href = '<%= institution_url(@institution) %>';
  $('#psap-institutions-page-content').html("<%= j render partial: 'institutions' %>");
<% else %>
  $('div#associate').remove();
<% end %>

app/views/institutions/index.html.erb
<% provide(:title, 'Institutions') %>
<% provide(:body_id, 'institutions') %>

<%= hidden_field_tag(:new_institution_url, new_institution_url) %>

<div class="pull-right">
  <%= entity_button(Institution, 'Add Institution',
                    { class: 'btn-success',
                      'data-toggle' => 'modal',
                      'data-target' => '#psap-create-panel' }) %>
</div>

<div class="psap-page-title">
  <h1>Institutions <small class="entity_count">
    <%= @institutions.total_entries %> total</small></h1>
</div>

<div id="psap-institutions-page-content">
  <%= render 'institutions' %>
</div>

<%= render partial: 'shared/edit_panel',
           locals: { action: :create, entity_name: 'Institution' } %>

app/views/institutions/index.js.erb
$('#psap-institutions-page-content').html('<%= escape_javascript(render('institutions')) %>');
$('.pagination a').attr('data-remote', 'true');

PSAP.updateResultsCount();

app/views/institutions/info.js.erb
// refresh info page content after a successful edit
$('#psap-institution-page-content').html("<%= j render partial: 'show' %>");
$('.psap-error-messages').empty();
$('.psap-page-title span#institution_name').text('<%= j @institution.name %>');

app/views/institutions/resources.js.erb
$('#resources').html('<%= escape_javascript(render partial: 'resources/resources',
                 locals: { resources: @resources,
                           show_checkboxes: false,
                           show_hierarchy: !@searching }) %>');
$('.pagination a').attr('data-remote', 'true');

app/views/institutions/show.html.erb
<% provide(:title, @institution.name) %>
<% provide(:body_id, 'show_institution') %>

<%= hidden_field_tag(:root_url, root_url) %>
<%= hidden_field_tag(:institution_url, institution_url(@institution)) %>

<% breadcrumbs = []
   breadcrumbs << { 'Institutions' => institutions_path } if current_user.is_admin?
   breadcrumbs << @institution.name %>
<%= breadcrumbs(breadcrumbs) %>

<div id="psap-institution-page-content">
  <%= render partial: 'show' %>
</div>

<%= render partial: 'shared/edit_panel',
           locals: { action: :edit, entity_name: 'Institution' } %>

<%= render partial: 'shared/edit_panel',
           locals: { action: :assess, entity_name: 'Institution' } %>

<%= render partial: 'shared/edit_panel',
           locals: { action: :create, entity_name: 'Repository' } %>