config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root 'static#landing'
  match '/about', to: 'static#about', via: :get, as: 'about'
  match '/assessment-report', to: 'assessment_report#index', via: :get,
        as: 'assessment_report'
  match '/assessment-report/collections', to: 'assessment_report#collections_section',
        via: :get
  match '/assessment-report/preservation', to: 'assessment_report#preservation_section',
        via: :get
  match '/assessment-report/resources', to: 'assessment_report#resources_section',
        via: :get
  match '/assessment-report/storage', to: 'assessment_report#storage_section',
        via: :get
  match '/bibliography', to: 'static#bibliography', via: :get
  match '/dashboard', to: 'dashboard#index', via: :get
  match '/getting-started', to: 'static#getting_started', via: :get
  match '/glossary', to: 'static#glossary', via: :get

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :formats, only: [:index, :show] do
    # used for populating the new/edit resource form with assessment questions
    resources :assessment_questions, only: :index, path: 'assessment-questions'
  end
  # used for dependent select menus in forms
  resources :format_classes, only: [], path: 'format-classes' do
    resources :formats, only: :index, path: 'formats'
  end
  resources :institutions do
    match '/assess', to: 'institutions#assess', via: :get
    resources :repositories, except: :index
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    match '/export', to: 'institutions#export', via: :get
    # these are used for form autocompletion
    match '/resources/names', to: 'resources#names', via: :get
    match '/resources/subjects', to: 'resources#subjects', via: :get
  end
  match '/institutions/:id/report', to: 'institutions#report', via: :get,
        as: 'institution_report'

  resources :repositories, except: :index do
    resources :locations, except: :index
  end
  resources :locations, except: :index do
    match '/assess', to: 'locations#assess', via: :get
    match '/resources/import', to: 'resources#import', via: :post,
          as: 'resource_import_post'
    match '/assessment-questions', to: 'assessment_questions#index', via: :get
    resources :resources, except: :index
  end
  match '/resources/move', to: 'resources#move', via: :post,
        as: 'resource_move'
  match '/resources/search', to: 'resources#search', via: :get,
        as: 'resource_search'
  resources :resources, except: :index do
    match '/assess', to: 'resources#assess', via: :get
    match '/clone', to: 'resources#clone', via: :patch, as: 'resource_clone'
    match '/import', to: 'resources#import', via: :post, as: 'import_post'
    match '/move-tree', to: 'resources#move_tree', via: :get
    resources :resources, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]

  resources :users, param: :username, path_names: { new: 'register' }
  match '/users/:username/confirm', to: 'users#confirm',
        via: :get, as: 'confirm_user'
  match '/users/:username/enable', to: 'users#enable',
        via: :patch, as: 'enable_user'
  match '/users/:username/disable', to: 'users#disable',
        via: :patch, as: 'disable_user'
  match '/users/:username/exists', to: 'users#exists',
        via: :get, as: 'user_exists'
  match '/users/:username/approve-institution', to: 'users#approve_institution',
        via: :patch, as: 'approve_user_institution'
  match '/users/:username/refuse-institution', to: 'users#refuse_institution',
        via: :patch, as: 'refuse_user_institution'
  match '/users/:username/send-confirmation-email',
        to: 'users#send_confirmation_email',
        via: :patch, as: 'send_confirmation_email'

  # Password routes
  # Step 1: "I forgot my password," click a button to POST to /forgot-password
  match '/forgot-password', to: 'password#forgot_password', via: :get
  match '/forgot-password', to: 'password#send_email', via: :post
  # Step 2: I click the link to /new-password in the email, then POST new
  # password to /new-password
  match '/new-password', to: 'password#new_password', via: :get
  match '/new-password', to: 'password#reset_password', via: :post

  # Collection ID Guide (formerly Format ID Guide) routes
  match '/collection-id-guide', to: 'collection_id_guide#index',
        via: :get, as: 'collection_id_guide'
  match '/collection-id-guide/search', to: 'collection_id_guide#search',
        via: :get, as: 'collection_id_guide_search'
  match '/collection-id-guide/:category', to: 'collection_id_guide#show',
        via: :get, as: 'collection_id_guide_category'

  # Redirect old Format ID Guide paths to Collection ID Guide paths
  get '/format-id-guide', to: redirect('/collection-id-guide')
  get '/format-id-guide/search', to: redirect('/collection-id-guide/search')
  get '/format-id-guide/:category', to: redirect('/collection-id-guide/%{category}')

  # Help routes
  match '/help', to: 'help#index', via: :get, as: 'help'
  match '/help/search', to: 'help#search', via: :get, as: 'help_search'
  match '/simple-help', to: 'help#simple_index', via: :get, as: 'simple_help'
  match '/advanced-help', to: 'help#advanced_index', via: :get,
        as: 'advanced_help'
  match '/advanced-help/:category', to: 'help#advanced_show', via: :get,
        as: 'advanced_help_category'
  match '/manual', to: 'help#manual', via: :get, as: 'user_manual'

end

app/models/repository.rb
##
# A Repository exists within an Institution. It can contain zero or more
# Locations.
#
# Repositories are not assessable.
#
class Repository < ApplicationRecord

  belongs_to :institution, inverse_of: :repositories
  has_many :locations, -> { order(:name) }, inverse_of: :repository,
           dependent: :destroy
  has_many :resources, -> { order(:name) }, through: :locations

  validates :institution, presence: true
  validates :name, presence: true, length: { maximum: 255 }

  validates_uniqueness_of :name, scope: :institution_id

  ##
  # Used by `Institution.import()`.
  #
  # @param struct [Hash]
  # @param location_id [Integer]
  # @return [Repository]
  #
  def self.import(struct, institution_id)
    repo = Repository.create!(created_at: struct['created_at'],
                              updated_at: struct['updated_at'],
                              institution_id: institution_id,
                              name: struct['name'])
    struct['locations'].each do |loc|
      Location.import(loc, repo.id)
    end
    repo
  end

  ##
  # @return [ActiveRecord::Relation<Resource>]
  #
  def collections
    self.resources.where(resource_type: Resource::Type::COLLECTION)
  end

  ##
  # Exports all of an instance's associated content.
  #
  # @see `Institution.full_export_as_json()`
  # @return [Hash]
  #
  def full_export_as_json
    struct = self.as_json
    struct[:locations] = self.locations.map { |loc| loc.full_export_as_json }
    struct
  end

end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController

  before_action :signed_in_user
  before_action :user_of_same_institution_or_admin,
                only: [:create, :destroy, :edit, :new, :show, :update]

  def create
    @institution = Institution.find(params[:institution_id])
    command = CreateRepositoryCommand.new(@institution, repository_params,
        current_user, request.remote_ip)
    @repository = command.object
    begin
      command.execute
    rescue ValidationError
      response.headers['X-Psap-Result'] = 'error'
      render partial: 'shared/validation_messages',
             locals: { entity: @repository }
    rescue => e
      response.headers['X-Psap-Result'] = 'error'
      flash['error'] = "#{e}"
      keep_flash
      render 'create'
    else
      response.headers['X-Psap-Result'] = 'success'
      flash['success'] = "Repository \"#{@repository.name}\" created."
      keep_flash
      render 'create'
    end
  end

  def destroy
    repository = Repository.find(params[:id])
    command = DeleteRepositoryCommand.new(repository,
                                          current_user, request.remote_ip)
    begin
      command.execute
    rescue => e
      flash['error'] = "#{e}"
      redirect_to repository
    else
      flash['success'] = "Repository \"#{repository.name}\" deleted."
      redirect_to repository.institution
    end
  end

  def edit
    if request.xhr?
      @repository = Repository.find(params[:id])
      render partial: 'edit_form', locals: { action: :edit }
    else
      render status: 406, plain: 'Not Acceptable'
    end
  end

  def new
    if request.xhr?
      @institution = Institution.find(params[:institution_id])
      @repository = @institution.repositories.build
      render partial: 'edit_form', locals: { action: :create }
    else
      render status: 406, plain: 'Not Acceptable'
    end
  end

  def show
    prepare_show_view
  end

  def update
    @repository = Repository.find(params[:id])
    command = UpdateRepositoryCommand.new(@repository, repository_params,
                                          current_user, request.remote_ip)
    begin
      command.execute
    rescue ValidationError
      response.headers['X-Psap-Result'] = 'error'
      render partial: 'shared/validation_messages',
             locals: { entity: @repository }
    rescue => e
      response.headers['X-Psap-Result'] = 'error'
      flash['error'] = "#{e}"
      render 'show'
    else
      prepare_show_view
      response.headers['X-Psap-Result'] = 'success'
      flash['success'] = "Repository \"#{@repository.name}\" updated."
      render 'show'
    end
  end

  private

  def prepare_show_view
    @repository = Repository.find(params[:id])
    @locations = @repository.locations.order(:name).
        paginate(page: params[:page],
                 per_page: ::Configuration.instance.results_per_page)
  end

  def user_of_same_institution_or_admin
    # Normal users can only modify repositories in their own institution.
    # Administrators can edit any repository.
    if params[:id]
      repository = Repository.find(params[:id])
      institution = repository.institution
    else
      institution = Institution.find(params[:institution_id])
    end
    redirect_to(root_url) unless
        institution.users.include?(current_user) || current_user.is_admin?
  end

  def repository_params
    params.require(:repository).permit(:name, :institution)
  end

end

app/views/repositories/_edit_form.html.erb
<%= form_for(@repository, remote: true) do |f| %>

  <div class="psap-error-messages">
    <% # populated via ajax by _show_error.js.erb
    %>
  </div>

  <div class="form-group">
    <%= f.label :name, class: 'required' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= hidden_field_tag(:institution_id, @repository.institution.id) %>

  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
  <%= f.submit(action == :create ? 'Create Repository' : 'Save Changes',
               class: 'btn btn-primary') %>

<% end %>

app/views/repositories/_locations.html.erb
<% # Will be read by PSAP.updateResultsCount() in JS %>
<input type="hidden" name="results_count" value="<%= @locations.total_entries %>">

<ul class="psap-entity-list">
  <% @locations.each do |location| %>
    <li>
      <span class="title">
        <%= entity_icon(location) %>
        <%= link_to location.name, location %>
      </span>
      <small>
        <%= entity_icon(Resource, pluralize(location.resources.count, 'resource')) %>
        <%= location.resources.count %>
      </small>
      <br>
      <span class="description"><%= location.description %></span>
    </li>
  <% end %>
</ul>

<div class="text-center">
  <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
</div>

app/views/repositories/_show.html.erb
<% breadcrumbs = []
   breadcrumbs << { 'Institutions' => institutions_path } if current_user.is_admin?
   breadcrumbs << { @repository.institution.name => @repository.institution }
   breadcrumbs << @repository.name %>
<%= breadcrumbs(breadcrumbs) %>

<div class="btn-group pull-right">
  <!-- Edit -->
  <button type="button" class="btn btn-default" data-toggle="modal"
          data-target="#psap-edit-panel">
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  </button>
  <!-- Delete -->
  <%= link_to repository_path(@repository), method: 'delete',
              class: 'btn btn-danger',
              data: { confirm: "Deleting this repository will delete all "\
                      "locations and resources it contains. "\
                      "Are you sure you want to delete this repository?\n\n"\
                      "⚠️ WARNING: THIS CANNOT BE UNDONE! ⚠️" } do %>
    <%= content_tag(:span, '', class: 'glyphicon glyphicon-trash') %>
    Delete
  <% end %>
</div>

<div class="psap-page-title">
  <h1><%= @repository.name %>
    <small class="text-nowrap"><%= entity_icon(@repository) %>Repository</small>
  </h1>
</div>

<div class="row">
  <div class="col-sm-4 psap-entity-nav-menu">
    <%= render partial: 'shared/entity_hierarchy',
               locals: { selected_entity: @repository }%>
  </div>

  <div class="col-sm-8">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#locations_tab" data-toggle="tab">Locations</a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="locations_tab">
        <div style="text-align:right">
          <%= entity_button(Location, 'Add Location',
                            { class: 'btn-success',
                              'data-toggle' => 'modal',
                              'data-target' => '#psap-create-panel' }) %>
        </div>
        <% if @repository.locations.any? %>
          <div id="locations">
            <%= render 'locations' %>
          </div>
        <% else %>
          <p>This repository has no locations.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/repositories/create.js.erb
// Rendered by RepositoriesController upon a successful create
//window.location.href = '<%= j repository_url(@repository) %>';
window.location.reload();

app/views/repositories/show.html.erb
<% provide(:title, @repository.name) %>
<% provide(:body_id, 'show_repository') %>

<%= hidden_field_tag(:repository_url, repository_url(@repository)) %>
<%= hidden_field_tag(:new_location_url, new_repository_location_url(@repository)) %>

<div id="psap-repository-page-content">
  <%= render partial: 'show' %>
</div>

<%= render partial: 'shared/edit_panel',
           locals: { action: :edit, entity_name: 'Repository' } %>

<%= render partial: 'shared/edit_panel',
           locals: { action: :create, entity_name: 'Location' } %>

app/views/repositories/show.js.erb
// refresh page content after a successful edit
$('#psap-repository-page-content').html("<%= j render partial: 'show' %>");
$('.psap-error-messages').empty();